name: filemanagerdx
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  provider: ^3.0.0
  rxdart: ^0.22.6
  path: ^1.6.2
  path_provider: ^1.1.0
  flutter_statusbarcolor: ^0.2.0
  shared_preferences: ^0.5.4+8
  toast: ^0.1.5
  share: ^0.6.1+1
  open_file: ^2.1.1
  url_launcher: ^5.2.7
  flutter_file_manager: ^0.1.1
  page_transition: ^1.1.0
  dynamic_theme: ^1.0.1
  package_info: ^0.4.0+12
  esys_flutter_share: ^1.0.2
  simple_permissions: ^0.1.9
  flutter_launcher_icons: ^0.7.4

  flutter_switch: ^0.2.1
  google_fonts: ^1.1.0
  fluttertoast: ^4.0.0
  country_code_picker: ^1.3.15
  pin_code_fields: 6.1.0
  #camera dependency
  camera: ^0.7.0+2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+17
  #firebase dependencies
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  firebase_database: ^4.1.0
  firebase_storage: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/launcher/new.png"
  android: true

flutter:
  uses-material-design: true

  fonts:
    - family: Gilroy_Bold
      fonts:
        - asset: assets/fonts/Gilroy_Bold.ttf
    - family: Gilroy_Medium
      fonts:
        - asset: assets/fonts/Gilroy_Medium.ttf
    - family: Gilroy_Regular
      fonts:
        - asset: assets/fonts/Gilroy_Regular.ttf

  assets:
    - assets/unknown_file_type2.png # source: https://www.iconfinder.com/icons/285688/empty_file_icon
    - assets/details.png
    - assets/languages/en.json
    - assets/languages/tr.json
    - assets/cities/cities.json
    - assets/images/
    - assets/pdfs/
